"""Food pairing suggestions for wine types and regions."""

PAIRINGS: dict[str, dict] = {
    "red": {
        "_default": {
            "foods": ["Carne vermelha grelhada", "Borrego assado", "Queijos curados", "Massas com molho de carne", "Enchidos ibéricos"],
            "avoid":  ["Peixe delicado", "Marisco", "Saladas leves"],
            "cuisines": ["Portuguesa", "Italiana", "Francesa clássica"],
            "ingredients": ["Carne vermelha", "Especiarias quentes", "Taninos"],
            "aeration": "Deixar arejar 30-60 minutos",
            "sommelier_tip": "Ótimo para pratos com molhos à base de vinho. Combina especialmente bem com carnes assadas lentamente.",
            "temp":   "16–18 °C",
            "glass":  "Copo Bordeaux (largo)",
        },
        "Douro": {
            "foods": ["Cabrito assado", "Posta mirandesa", "Queijo da Serra", "Leitão à Bairrada", "Migas alentejanas"],
            "avoid": ["Frutos do mar", "Sushi"],
            "cuisines": ["Portuguesa tradicional", "Minhota", "Transmontana"],
            "ingredients": ["Carnes assadas", "Especiarias portuguesas", "Queijo de pasta dura"],
            "aeration": "30 minutos de arejação",
            "sommelier_tip": "Perfeito para a culinária portuguesa rústica. O Douro é a expressão máxima da gastronomia regional.",
            "temp":  "17–19 °C",
            "glass": "Copo Bordeaux (largo)",
        },
        "Alentejo": {
            "foods": ["Porco preto alentejano", "Açorda alentejana", "Queijo de Évora", "Borrego à pastora", "Chouriço assado"],
            "avoid": ["Peixe branco", "Saladas"],
            "cuisines": ["Alentejana", "Portuguesa do interior"],
            "ingredients": ["Porco ibérico", "Pão à alentejana", "Alho e coentros"],
            "aeration": "20-30 minutos",
            "sommelier_tip": "Vinho robusto para pratos robusto. Ideal para jantares informais ao ar livre.",
            "temp":  "16–18 °C",
            "glass": "Copo Bordeaux",
        },
        "Bordeaux": {
            "foods": ["Entrecôte grelhado", "Cordeiro assado", "Foie gras", "Trufas", "Queijo Comté"],
            "avoid": ["Frutos do mar", "Pratos ácidos"],
            "cuisines": ["Francesa clássica", "Francesa gourmet"],
            "ingredients": ["Carnes nobres", "Trufas", "Molhos encorpados"],
            "aeration": "45-90 minutos (especialmente vinhos jovens)",
            "sommelier_tip": "Estrutura e elegância. Perfeito para ocasiões especiais com carnes premium.",
            "temp":  "17–19 °C",
            "glass": "Copo Bordeaux (largo)",
        },
        "Tuscany": {
            "foods": ["Bistecca alla fiorentina", "Pasta al ragù", "Parmigiano-Reggiano", "Cinghiale", "Tartufo nero"],
            "avoid": ["Peixe", "Pratos doces"],
            "cuisines": ["Italiana da Toscana", "Rústica italiana"],
            "ingredients": ["Carnes vermelhas italianas", "Trufas negras", "Azeite de oliva"],
            "aeration": "30-60 minutos",
            "sommelier_tip": "O vinho toscano é sinónimo da Itália rural. Perfeito com pratos de carne grelhada.",
            "temp":  "17–19 °C",
            "glass": "Copo Burgundy",
        },
        "Burgundy": {
            "foods": ["Coq au vin", "Boeuf bourguignon", "Queijo Époisses", "Cogumelos selvagens", "Pato assado"],
            "avoid": ["Peixe branco", "Pratos muito picantes"],
            "cuisines": ["Francesa clássica", "Borgonha tradicional"],
            "ingredients": ["Carnes em vinho tinto", "Cogumelos", "Molhos cremosos"],
            "aeration": "20-45 minutos",
            "sommelier_tip": "Elegância francesa. Ideal para jantares sofisticados com pratos de cozinha lenta.",
            "temp":  "15–17 °C",
            "glass": "Copo Burgundy (largo e arredondado)",
        },
    },
    "white": {
        "_default": {
            "foods": ["Peixe grelhado", "Marisco", "Queijos frescos", "Saladas", "Aves em molho creme"],
            "avoid": ["Carne vermelha", "Enchidos fortes"],
            "cuisines": ["Francesa", "Portuguesa do litoral"],
            "ingredients": ["Peixe branco", "Marisco", "Manteiga e creme"],
            "aeration": "Servir direto do frigorífico",
            "sommelier_tip": "Fresco e elegante. Perfeito para refeições ao meio-dia ou jantares leves.",
            "temp":  "8–12 °C",
            "glass": "Copo Chardonnay",
        },
        "Vinho Verde": {
            "foods": ["Sardinhas grelhadas", "Bacalhau à brás", "Percebes", "Mexilhões", "Salada de polvo"],
            "avoid": ["Carne vermelha", "Queijos curados intensos"],
            "cuisines": ["Portuguesa costeira", "Minhota"],
            "ingredients": ["Peixe do Atlântico", "Marisco fresco", "Limão"],
            "aeration": "Nenhuma",
            "sommelier_tip": "O vinho verde é uma celebração das praias portuguesas. Beber jovem, fresco e com entusiasmo.",
            "temp":  "8–10 °C",
            "glass": "Copo branco pequeno",
        },
        "Burgundy": {
            "foods": ["Lagosta", "Ostras", "Lulas salteadas", "Queijo Brie", "Frango assado"],
            "avoid": ["Carnes vermelhas", "Pratos muito condimentados"],
            "cuisines": ["Francesa sofisticada", "Borgonha"],
            "ingredients": ["Marisco fino", "Manteiga", "Ervas aromáticas"],
            "aeration": "Nenhuma, servir fresco",
            "sommelier_tip": "Branco de enorme elegância. Para ocasiões onde a sofisticação é prioritária.",
            "temp":  "10–13 °C",
            "glass": "Copo Chardonnay (amplo)",
        },
    },
    "sparkling": {
        "_default": {
            "foods": ["Ostras", "Canapés", "Sushi", "Frutos secos", "Mousse de salmão", "Queijo brie"],
            "avoid": ["Pratos muito pesados", "Sobremesas muito doces (excepto Demi-Sec)"],
            "cuisines": ["Celebração", "Aperitivo francês"],
            "ingredients": ["Ostras", "Caviar", "Salmão fumado"],
            "aeration": "Nenhuma",
            "sommelier_tip": "O perfeito acompanhante para celebrações. As bolhas crescem com comida leve e elegante.",
            "temp":  "6–9 °C",
            "glass": "Flûte ou copo tulipa",
        },
        "Champagne": {
            "foods": ["Caviar", "Foie gras", "Lagosta", "Ostras", "Risotto de trufas", "Queijo de cabra"],
            "avoid": ["Sobremesas achocolatadas", "Pratos com vinagre"],
            "cuisines": ["Francesa gourmet", "Champagne clássica"],
            "ingredients": ["Caviar russo", "Foie gras francês", "Trufas brancas"],
            "aeration": "Nenhuma",
            "sommelier_tip": "Símbolo de luxo e celebração. Cada bolha é uma expressão de prestígio.",
            "temp":  "6–8 °C",
            "glass": "Flûte Champagne",
        },
    },
    "rosé": {
        "_default": {
            "foods": ["Charcutaria", "Saladas niçoises", "Pizzas", "Salmão grelhado", "Queijo de cabra", "Ratatouille"],
            "avoid": ["Carnes vermelhas muito pesadas", "Ostras"],
            "cuisines": ["Mediterrânea", "Francesa do Côte d'Azur"],
            "ingredients": ["Frutas vermelhas", "Ervas aromáticas", "Peixes leves"],
            "aeration": "Nenhuma",
            "sommelier_tip": "Versátil e refrescante. Perfeito para refeições casuais e ao ar livre.",
            "temp":  "8–12 °C",
            "glass": "Copo branco padrão",
        },
    },
    "fortified": {
        "_default": {
            "foods": ["Queijo stilton", "Chocolate negro", "Nozes", "Tâmaras", "Figos secos", "Foie gras"],
            "avoid": ["Peixe delicado", "Saladas"],
            "cuisines": ["Portuguesa", "Britânica"],
            "ingredients": ["Frutos secos", "Queijos fortes", "Chocolate"],
            "aeration": "30 minutos se muito jovem",
            "sommelier_tip": "Complexidade e profundidade. Ideal para após-refeição meditativo.",
            "temp":  "14–18 °C (tawny) / 12–14 °C (ruby)",
            "glass": "Copo Porto (pequeno tulipa)",
        },
    },
    "dessert": {
        "_default": {
            "foods": ["Foie gras", "Queijo Roquefort", "Pastel de nata", "Tarte de maçã", "Pêssego grelhado", "Sorvete de baunilha"],
            "avoid": ["Pratos salgados fortes", "Carnes vermelhas"],
            "cuisines": ["Francesa clássica", "Portuguesa tradicional"],
            "ingredients": ["Frutas doces", "Mel", "Especiarias"],
            "aeration": "Nenhuma",
            "sommelier_tip": "Doçura e elegância. Perfeito para acompanhar sobremesas ou em final de refeição.",
            "temp":  "6–10 °C",
            "glass": "Copo pequeno de sobremesa",
        },
    },
}


def get_pairing(wine_type: str, region: str) -> dict:
    """Return food pairing suggestions for a wine."""
    type_rules = PAIRINGS.get(wine_type, PAIRINGS.get("red", {}))
    pairing    = type_rules.get(region) or type_rules.get("_default", {})
    return {
        "foods": pairing.get("foods", []),
        "avoid": pairing.get("avoid", []),
        "cuisines": pairing.get("cuisines", []),
        "ingredients": pairing.get("ingredients", []),
        "aeration": pairing.get("aeration", "Nenhuma"),
        "sommelier_tip": pairing.get("sommelier_tip", ""),
        "serving_temp": pairing.get("temp", "Ver recomendação"),
        "glass_type":   pairing.get("glass", "Copo padrão"),
    }
